package consts

const ClashProfileItemPort = "port"
const ClashProfileItemSocksPort = "socks-port"
const ClashProfileItemMixedPort = "mixed-port"
const ClashProfileItemAllowLan = "allow-lan"
const ClashProfileItemMode = "mode"
const ClashProfileItemLogLevel = "log-level"
const ClashProfileItemExternalController = "external-controller"
const ClashProfileItemExperimental = "experimental"
const ClashProfileItemDns = "dns"
const ClashProfileItemCFWLatencyTimeout = "cfw-latency-timeout"
const ClashProfileItemCFWLatencyUrl = "cfw-latency-url"
const ClashProfileItemCFWConnBreakStrategy = "cfw-conn-break-strategy"
const ClashProfileItemScript = "script"
const ClashProfileItemRuleProviders = "rule-providers"
const ClashProfileItemCFWBypass = "cfw-bypass"
const ClashProfileItemProxies = "proxies"
const ClashProfileItemProxyGroups = "proxy-groups"
const ClashProfileItemRules = "rules"
